kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-*******
  directoryPerms: "700"

  ### Use this yaml while creating the storage class, provisioning the storage to pvc is the desired functionality.