apiVersion: v1
kind: PersistentVolume
metadata:
  name: efspv
spec:
  capacity:
    storage: 9Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi: 
    driver: efs.csi.aws.com
    volumeHandle: fs-04446c396c24c56a1