apiVersion: v1
kind: Pod
metadata:
  name: food
  labels:
    app: food
spec:
  volumes:
  - name: webdata
    hostPath:
      path: /root/food
  containers:
  - name: food
    image: ubuntu/apache2
    volumeMounts:
    - name: webdata
      mountPath: /var/www/html
 
