apiVersion: v1
kind: Pod
metadata:
  name: food
  labels:
    app: food
spec:
  volumes:
  - name: webdata
    hostPath:
      path: /root/food
  containers:
  - name: food
    image: ubuntu/apache2
    volumeMounts:
    - name: webdata
      mountPath: /var/www/html
    ports:
    - containerPort: 80
      hostPort: 8000

#      Before executing this script, execute "git clone https://github.com/sharma04500/food.git"
# as a root user, in order to clone the repo 'food' into the root directory to make the source code
# available in the hostPath as specified in the above yaml code.
 
