apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    for: jenkins
    to: agent    
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts
      ports:
      - containerPort: 8080
      - containerPort: 31999

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  type: NodePort
  selector:
    for: jenkins
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 32000

---
apiVersion: v1
kind: Service
metadata:
  name: agent-svc
spec:
  type: NodePort
  selector: 
    to: agent
  ports:
  - protocol: TCP
    port: 31999
    targetPort: 31999
    nodePort: 31999

#################################################################################
#################################################################################
###       while writing labels for enabling the pod to be identified by two objects,
### both the values being used in key and value fields of both the labels must
### be unique.
###       Before attempting to connect from the agent to the jenkins master, do open
### the port 31999 in the security group from anywhere and also make sure that
### the default TCP value for jenkins agent under the Manage Jenkins > Security 
### is set to 31999, or else the downloaded agent.jar file will by default attempt
### to establish the connection to master via 50000 by default and the request gets
### failed as the port 50000 will not be accessible either at pod or node level. 
#######################################################################################
#######################################################################################
