apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    for: jenkins
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts
      ports:
      - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  type: NodePort
  selector:
    for: jenkins
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 32000
