apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    for: jenkins
    to: agent    
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts
      ports:
      - containerPort: 8080
      - containerPort: 52000

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  type: NodePort
  selector:
    for: jenkins
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 32000

---
apiVersion: v1
kind: Service
metadata:
  name: agent-svc
spec:
  type: NodePort
  selector: 
    to: agent
  ports:
  - protocol: TCP
    port: 52000
    targetPort: 52000
    nodePort: 31999

#############################################################################
##############################################################################
###   while using labels for enabling the pod to be identified by two objects,
### both the values being used in key and value fields of both the labels must
### be unique.
################################################################################
#################################################################################
