apiVersion: v1
kind: Pod
metadata: 
  name: dummy
  labels:
    requirement: testing-pvc
    app: food
spec:
  containers:
    - name: nothing
      image: ubuntu/apache2
      volumeMounts:
        - name: firstpod
          mountPath: /var/www/html
      ports:
        - containerPort: 80
          hostPort: 2000
          name: http
  volumes:
    - name: firstpod
      persistentVolumeClaim:
        claimName: binladen
  