apiVersion: v1
kind: Pod
metadata:
  name: trail
  labels:
    requirement: testing
spec:
  volumes:
    - name: food
      emptyDir: {}
  containers:
    - name: food
      image: ubuntu/apache2
      volumeMounts:
      - name: food
        mountPath: /var/www/html
      ports:
      - containerPort: 80
        hostPort: 8000


###############################################################################################
###############################################################################################
###
###   EmptyDir is a volume plugin, supported by k8s. emptyDir creates an empty volume in the 
### kubelet's data directory under the path "/var/lib/kubelet/pod/<pod_ID>/volumes/ " in the node
### on which the pod is running.
###   The data being written in the container will be written to this directory and the data 
### persists, even if a container in the pod goes down.
###   But, if the entire pod was deleted, the directory will also get deleted alongwith the pod.
### So, it is not a recommended solution to use this emptyDir plugin, though it is providing a 
### solution to store the data outside the pod {containers}, which are epphimeral in nature.
###
### For more INFO: https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
################################################################################################
################################################################################################
